// <auto-generated />
using System;
using Fatura.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fatura.Migrations
{
    [DbContext(typeof(xstoreContext))]
    [Migration("20260112064956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fatura.Models.Auditoria.HistorialTransaccion", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datos_adicionales");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_transaccion");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int>("IdUsuarioEmisor")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_emisor");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<int>("TipoTransaccion")
                        .HasColumnType("int")
                        .HasColumnName("tipo_transaccion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdHistorial")
                        .HasName("pk_historial_transaccion");

                    b.HasIndex("FechaTransaccion")
                        .HasDatabaseName("idx_historial_transaccion_fecha_transaccion");

                    b.HasIndex("IdCliente")
                        .HasDatabaseName("idx_historial_transaccion_id_cliente");

                    b.HasIndex("IdFactura")
                        .HasDatabaseName("idx_historial_transaccion_id_factura");

                    b.HasIndex("IdUsuarioEmisor")
                        .HasDatabaseName("idx_historial_transaccion_id_usuario_emisor");

                    b.HasIndex("TipoTransaccion")
                        .HasDatabaseName("idx_historial_transaccion_tipo_transaccion");

                    b.ToTable("historial_transaccion", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_categoria");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdCategoria")
                        .HasName("pk_categoria");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_marca");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdMarca")
                        .HasName("pk_marca");

                    b.ToTable("marca", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<bool>("RequiereReferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("requiere_referencia");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdMetodoPago")
                        .HasName("pk_metodo_pago");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uk_metodo_pago_nombre");

                    b.ToTable("metodo_pago", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<int?>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.Property<int>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_minimo");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdProducto")
                        .HasName("pk_producto");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uk_producto_codigo")
                        .HasFilter("[codigo] IS NOT NULL");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.ProductoImpuesto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdTipoImpuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_impuesto");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PorcentajePersonalizado")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_personalizado");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdProducto", "IdTipoImpuesto")
                        .HasName("pk_producto_impuesto");

                    b.HasIndex("IdTipoImpuesto");

                    b.ToTable("producto_impuesto", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.TipoImpuesto", b =>
                {
                    b.Property<int>("IdTipoImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_impuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoImpuesto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<bool>("AplicaProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aplica_productos");

                    b.Property<bool>("AplicaServicios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("aplica_servicios");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdTipoImpuesto")
                        .HasName("pk_tipo_impuesto");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uk_tipo_impuesto_nombre");

                    b.ToTable("tipo_impuesto", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidadMedida"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("abreviatura");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdUnidadMedida")
                        .HasName("pk_unidad_medida");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uk_unidad_medida_nombre");

                    b.ToTable("unidad_medida", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NitDui")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nit_dui");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_cliente_email");

                    b.HasIndex("NitDui")
                        .IsUnique()
                        .HasDatabaseName("uk_cliente_nit_dui");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.DetalleFactura", b =>
                {
                    b.Property<int>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleFactura"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unidad_medida");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleFactura")
                        .HasName("pk_detalle_factura");

                    b.HasIndex("IdFactura")
                        .HasDatabaseName("idx_detalle_factura_id_factura");

                    b.HasIndex("IdProducto")
                        .HasDatabaseName("idx_detalle_factura_id_producto");

                    b.ToTable("detalle_factura", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.DetalleFacturaImpuesto", b =>
                {
                    b.Property<int>("IdDetalleFacturaImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_factura_impuesto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleFacturaImpuesto"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleFactura")
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_factura");

                    b.Property<int>("IdTipoImpuesto")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_impuesto");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MontoImpuesto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_impuesto");

                    b.Property<string>("NombreImpuesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_impuesto");

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleFacturaImpuesto")
                        .HasName("pk_detalle_factura_impuesto");

                    b.HasIndex("IdDetalleFactura")
                        .HasDatabaseName("idx_detalle_factura_impuesto_id_detalle_factura");

                    b.HasIndex("IdTipoImpuesto");

                    b.ToTable("detalle_factura_impuesto", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_factura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("CaiDte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cai_dte");

                    b.Property<string>("ClienteDireccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("cliente_direccion");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("ClienteNitDui")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("cliente_nit_dui");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("cliente_nombre");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaLimiteEmision")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_limite_emision");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pago");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int?>("IdMetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("id_metodo_pago");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Isr")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("isr");

                    b.Property<decimal>("Iva")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("iva");

                    b.Property<string>("MonedaSimbolo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasDefaultValue("$")
                        .HasColumnName("moneda_simbolo");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<decimal>("OtrosImpuestos")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("otros_impuestos");

                    b.Property<string>("ReferenciaMetodoPago")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("referencia_metodo_pago");

                    b.Property<string>("SerieFactura")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("serie_factura");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("sub_total");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Factura")
                        .HasColumnName("tipo_documento");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("IdFactura")
                        .HasName("pk_factura");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("idx_factura_cliente_id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_factura_estado");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("idx_factura_fecha_creacion");

                    b.HasIndex("IdMetodoPago")
                        .HasDatabaseName("idx_factura_id_metodo_pago");

                    b.HasIndex("NumeroFactura")
                        .IsUnique()
                        .HasDatabaseName("uk_factura_numero_factura");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_factura_usuario_id");

                    b.ToTable("factura", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Identity.ConfiguracionDashboard", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_configuracion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("MostrarClientesActivos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("mostrar_clientes_activos");

                    b.Property<bool>("MostrarFacturasEmitidas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("mostrar_facturas_emitidas");

                    b.Property<bool>("MostrarFacturasRecientes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("mostrar_facturas_recientes");

                    b.Property<bool>("MostrarIngresosMensuales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("mostrar_ingresos_mensuales");

                    b.Property<bool>("MostrarIngresosMes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("mostrar_ingresos_mes");

                    b.Property<bool>("MostrarTasaCobro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("mostrar_tasa_cobro");

                    b.Property<int>("PeriodoGraficoMeses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(7)
                        .HasColumnName("periodo_grafico_meses");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdConfiguracion")
                        .HasName("pk_configuracion_dashboard");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("uk_configuracion_dashboard_usuario");

                    b.ToTable("configuracion_dashboard", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uk_role_nombre");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Identity.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contraseña_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Salt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("salt");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultimo_acceso");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uk_usuario_email");

                    b.HasIndex("NombreUsuario")
                        .HasDatabaseName("idx_usuario_nombre_usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Identity.UsuarioRole", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AsignadoEn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("asignado_en");

                    b.HasKey("UsuarioId", "RoleId")
                        .HasName("pk_usuario_role");

                    b.HasIndex("RoleId");

                    b.ToTable("usuario_role", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Auditoria.HistorialTransaccion", b =>
                {
                    b.HasOne("Fatura.Models.Facturacion.Cliente", "Cliente")
                        .WithMany("HistorialTransacciones")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_historial_transaccion_cliente");

                    b.HasOne("Fatura.Models.Facturacion.Factura", "Factura")
                        .WithMany("HistorialTransacciones")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_historial_transaccion_factura");

                    b.HasOne("Fatura.Models.Identity.Usuario", "UsuarioEmisor")
                        .WithMany("HistorialTransacciones")
                        .HasForeignKey("IdUsuarioEmisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historial_transaccion_usuario");

                    b.Navigation("Cliente");

                    b.Navigation("Factura");

                    b.Navigation("UsuarioEmisor");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.Producto", b =>
                {
                    b.HasOne("Fatura.Models.Catalogos.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_producto_categoria");

                    b.HasOne("Fatura.Models.Catalogos.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_producto_marca");

                    b.HasOne("Fatura.Models.Catalogos.UnidadMedida", "UnidadMedida")
                        .WithMany("Productos")
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_producto_unidad_medida");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.ProductoImpuesto", b =>
                {
                    b.HasOne("Fatura.Models.Catalogos.Producto", "Producto")
                        .WithMany("ProductoImpuestos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_producto_impuesto_producto");

                    b.HasOne("Fatura.Models.Catalogos.TipoImpuesto", "TipoImpuesto")
                        .WithMany("ProductoImpuestos")
                        .HasForeignKey("IdTipoImpuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_producto_impuesto_tipo_impuesto");

                    b.Navigation("Producto");

                    b.Navigation("TipoImpuesto");
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.DetalleFactura", b =>
                {
                    b.HasOne("Fatura.Models.Facturacion.Factura", "Factura")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_factura_factura");

                    b.HasOne("Fatura.Models.Catalogos.Producto", "Producto")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_detalle_factura_producto");

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.DetalleFacturaImpuesto", b =>
                {
                    b.HasOne("Fatura.Models.Facturacion.DetalleFactura", "DetalleFactura")
                        .WithMany("Impuestos")
                        .HasForeignKey("IdDetalleFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_factura_impuesto_detalle_factura");

                    b.HasOne("Fatura.Models.Catalogos.TipoImpuesto", "TipoImpuesto")
                        .WithMany("DetalleFacturaImpuestos")
                        .HasForeignKey("IdTipoImpuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_factura_impuesto_tipo_impuesto");

                    b.Navigation("DetalleFactura");

                    b.Navigation("TipoImpuesto");
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.Factura", b =>
                {
                    b.HasOne("Fatura.Models.Facturacion.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_factura_cliente");

                    b.HasOne("Fatura.Models.Catalogos.MetodoPago", "MetodoPago")
                        .WithMany("Facturas")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_factura_metodo_pago");

                    b.HasOne("Fatura.Models.Identity.Usuario", "Usuario")
                        .WithMany("Facturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_factura_usuario");

                    b.Navigation("Cliente");

                    b.Navigation("MetodoPago");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fatura.Models.Identity.ConfiguracionDashboard", b =>
                {
                    b.HasOne("Fatura.Models.Identity.Usuario", "Usuario")
                        .WithOne("ConfiguracionDashboard")
                        .HasForeignKey("Fatura.Models.Identity.ConfiguracionDashboard", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_configuracion_dashboard_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fatura.Models.Identity.UsuarioRole", b =>
                {
                    b.HasOne("Fatura.Models.Identity.Role", "Role")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_role_role");

                    b.HasOne("Fatura.Models.Identity.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_role_usuario");

                    b.Navigation("Role");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.MetodoPago", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.Producto", b =>
                {
                    b.Navigation("DetalleFacturas");

                    b.Navigation("ProductoImpuestos");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.TipoImpuesto", b =>
                {
                    b.Navigation("DetalleFacturaImpuestos");

                    b.Navigation("ProductoImpuestos");
                });

            modelBuilder.Entity("Fatura.Models.Catalogos.UnidadMedida", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("HistorialTransacciones");
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.DetalleFactura", b =>
                {
                    b.Navigation("Impuestos");
                });

            modelBuilder.Entity("Fatura.Models.Facturacion.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");

                    b.Navigation("HistorialTransacciones");
                });

            modelBuilder.Entity("Fatura.Models.Identity.Role", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Fatura.Models.Identity.Usuario", b =>
                {
                    b.Navigation("ConfiguracionDashboard");

                    b.Navigation("Facturas");

                    b.Navigation("HistorialTransacciones");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
