// <auto-generated />
using System;
using Fatura.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fatura.Migrations
{
    [DbContext(typeof(xstoreContext))]
    partial class xstoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fatura.Models.Categorium", b =>
                {
                    b.Property<int>("Idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDCategoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcategoria"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Idcategoria")
                        .HasName("PK__Categori__70E82E28335B1CB4");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Fatura.Models.DetalleFactura", b =>
                {
                    b.Property<int>("IddetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDDetalleFactura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IddetalleFactura"));

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime");

                    b.Property<int?>("Idfactura")
                        .HasColumnType("integer")
                        .HasColumnName("IDFactura");

                    b.Property<int?>("Idproducto")
                        .HasColumnType("integer")
                        .HasColumnName("IDProducto");

                    b.Property<decimal?>("Total")
                        .HasColumnType("money");

                    b.HasKey("IddetalleFactura")
                        .HasName("PK__DetalleF__EF0E5D9A0E87D534");

                    b.HasIndex("Idfactura");

                    b.HasIndex("Idproducto");

                    b.ToTable("DetalleFactura", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Factura", b =>
                {
                    b.Property<int>("Idfactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDFactura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idfactura"));

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Total")
                        .HasColumnType("money");

                    b.HasKey("Idfactura")
                        .HasName("PK__Factura__492FE9390232D7A0");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Marca", b =>
                {
                    b.Property<int>("Idmarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDMarca");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idmarca"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Idmarca")
                        .HasName("PK__Marca__CEC375E729BA7C81");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Producto", b =>
                {
                    b.Property<int>("Idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDProducto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idproducto"));

                    b.Property<int?>("Codigo")
                        .HasColumnType("integer")
                        .HasColumnName("codigo");

                    b.Property<int?>("Idcategoria")
                        .HasColumnType("integer")
                        .HasColumnName("IDCategoria");

                    b.Property<int?>("Idmarca")
                        .HasColumnType("integer")
                        .HasColumnName("IDMarca");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("Precio")
                        .HasColumnType("double precision")
                        .HasColumnName("precio");

                    b.HasKey("Idproducto")
                        .HasName("PK__Producto__ABDAF2B48FF32BD9");

                    b.HasIndex("Idcategoria");

                    b.HasIndex("Idmarca");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.Usuario", b =>
                {
                    b.Property<int>("Idusurio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IDUsurio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idusurio"));

                    b.Property<int?>("Contraseña")
                        .HasColumnType("integer");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("NombreUSuario");

                    b.HasKey("Idusurio")
                        .HasName("PK__Usuario__60FD6F4FAA1CC3B0");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Fatura.Models.DetalleFactura", b =>
                {
                    b.HasOne("Fatura.Models.Factura", "IdfacturaNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("Idfactura")
                        .HasConstraintName("FK__DetalleFa__IDFac__33D4B598");

                    b.HasOne("Fatura.Models.Producto", "IdproductoNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("Idproducto")
                        .HasConstraintName("FK__DetalleFa__IDPro__34C8D9D1");

                    b.Navigation("IdfacturaNavigation");

                    b.Navigation("IdproductoNavigation");
                });

            modelBuilder.Entity("Fatura.Models.Producto", b =>
                {
                    b.HasOne("Fatura.Models.Categorium", "IdcategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("Idcategoria")
                        .HasConstraintName("FK__Producto__IDCate__2F10007B");

                    b.HasOne("Fatura.Models.Marca", "IdmarcaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("Idmarca")
                        .HasConstraintName("FK__Producto__IDMarc__2E1BDC42");

                    b.Navigation("IdcategoriaNavigation");

                    b.Navigation("IdmarcaNavigation");
                });

            modelBuilder.Entity("Fatura.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Fatura.Models.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("Fatura.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Fatura.Models.Producto", b =>
                {
                    b.Navigation("DetalleFacturas");
                });
#pragma warning restore 612, 618
        }
    }
}
